// ESLint, flat config — the only format ESLint 10 reads.
//
// Scoped to `src/` on purpose. The Rust crates have rustfmt and clippy, and
// `src-tauri` holds no TypeScript; pointing a JavaScript linter at them would
// only produce noise about files it cannot understand.
//
// Formatting rules are deliberately absent. Prettier owns layout, and a linter
// that also has opinions about it produces two tools disagreeing about the same
// line — `eslint-config-prettier` at the end turns off every rule that would.

import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "target/**",
      "node_modules/**",
      "src-tauri/**",
      "crates/**",
      // Generated by the Tauri mobile templates, not written here.
      "src-tauri/gen/**",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs["recommended-latest"].rules,

      // Fast Refresh can only replace a module that exports components alone.
      // A warning rather than an error: a file that also exports a helper still
      // works, it just reloads the whole page.
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],

      // Downgraded from error, deliberately and not permanently.
      //
      // Every one of the ten places this fires is a working, idiomatic pattern:
      // reset a field when a dialog opens, fetch when a panel mounts. The rule
      // is a stricter standard aimed at React Compiler readiness, and it is
      // right that each costs an extra render pass — but clearing them means
      // rewriting ten components around `key` resets and different data-loading
      // shapes, which is a considered piece of work rather than something to do
      // on a linter's schedule while installing it.
      //
      // Left visible as warnings rather than silenced: the point is that the
      // list is short, named, and shrinks.
      "react-hooks/set-state-in-effect": "warn",

      // An unused parameter is often deliberate — a callback that must match a
      // signature it does not use every argument of. Underscore is the
      // convention for saying so.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },

  // Config files run in Node, not the browser.
  {
    files: ["*.config.{ts,js}", "vite.config.ts"],
    languageOptions: { globals: globals.node },
  },

  prettier,
);
